# Generated by Django 4.1.1 on 2023-08-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenserecord",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="expenserecord",
            name="debt_amount",
            field=models.IntegerField(default=0),
        ),
    ]
