# Generated by Django 4.1.1 on 2023-08-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_expenserecord_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordsBackup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("records", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Back-Up",
                "verbose_name_plural": "Back-Ups",
            },
        ),
    ]
