# Generated by Django 4.1.1 on 2023-08-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_recordsbackup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordsbackup",
            name="records",
            field=models.CharField(max_length=100000),
        ),
    ]
