# Generated by Django 4.1.1 on 2023-08-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_recordsbackup_records"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordsbackup",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
